[package]
name = "computer"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ollama-rs = { version = "0.2.0", features = [
    "stream",
    "chat-history",
    "function-calling",
] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
